server.port     : ":8000"
server.api_key  : "davidchandra95"
# Chose a database : mysql || postgres
server.database : "postgres"

mysql.host      : "127.0.0.1"
mysql.port      : "3306"
mysql.database  : ""
mysql.username  : ""
mysql.password  : ""

psql.host       : "localhost"
psql.port       : "5432"
psql.database   : "go-laundry"
psql.username   : "admin"
psql.password   : "admin123"
psql.sslmode    : "disable"